name: WSSF2023
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
timezone: Asia/Shanghai
livereload: true
baseurl: https://estds.yicode.ac
cfrc_start: 2023-04-24
cfrc_end: 2023-04-26
cfrc_place: Nanjing, China
cfrc_place_zh: 中国·南京
